"""
CAN-001 – CAN-007: /cancel and /unsubscribe route tests.

Verifies that cancel and unsubscribe URLs generated by email.py never return 404,
that GET /cancel shows a confirmation page (not immediate deletion), and that POST
/cancel executes cancellation with token invalidation on second use.
"""
import re

import pytest
from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


# ── CAN-001: /cancel GET returns 200 (confirmation page, not 404) ─────────

def test_can001_cancel_get_not_404():
    """/cancel GET must return 200 regardless of token validity — it only shows
    a confirmation page so email prefetch never cancels subscriptions."""
    r = client.get("/cancel?token=nonexistent_token_abc")
    assert r.status_code == 200, f"Expected 200 (confirm page), got {r.status_code}"
    assert "cancel" in r.text.lower()


def test_can001_cancel_get_without_token():
    """/cancel GET with no token must still return 200."""
    r = client.get("/cancel")
    assert r.status_code == 200


# ── CAN-002: /unsubscribe GET returns 200 ────────────────────────────────

def test_can002_unsubscribe_get_not_404():
    """/unsubscribe GET must return 200 so the URL in emails never 404s."""
    r = client.get("/unsubscribe")
    assert r.status_code == 200, f"Expected 200, got {r.status_code}"
    assert "unsubscribe" in r.text.lower()


# ── CAN-003: POST /cancel with valid token cancels subscription ──────────

def test_can003_post_cancel_with_valid_token():
    """POST /cancel?token=VALID_TOKEN removes the subscription and returns 200."""
    from app.db import add_watch, get_emails_for, get_or_create_cancel_token

    add_watch("CancelTest_Person", "canceltest@example.com")
    token = get_or_create_cancel_token("CancelTest_Person", "canceltest@example.com")

    r = client.post(f"/cancel?token={token}")
    assert r.status_code == 200
    assert "cancelled" in r.text.lower() or "unsubscribed" in r.text.lower()

    # Subscription must be gone
    remaining = get_emails_for("CancelTest_Person")
    assert "canceltest@example.com" not in remaining


# ── CAN-004: token rejected on second use ───────────────────────────────

def test_can004_token_rejected_on_second_use():
    """A cancel token is one-time: the second POST must not succeed."""
    from app.db import add_watch, get_or_create_cancel_token

    add_watch("SecondUse_Person", "seconduse@example.com")
    token = get_or_create_cancel_token("SecondUse_Person", "seconduse@example.com")

    r1 = client.post(f"/cancel?token={token}")
    assert r1.status_code == 200

    r2 = client.post(f"/cancel?token={token}")
    assert r2.status_code == 200
    # Second attempt must say "already used" or "invalid", not "cancelled"
    assert (
        "already" in r2.text.lower()
        or "invalid" in r2.text.lower()
        or "not found" in r2.text.lower()
    ), f"Expected invalid-token message, got: {r2.text[:200]}"


# ── CAN-005: /watch response includes cancel_url ─────────────────────────

def test_can005_watch_response_includes_cancel_url():
    """POST /watch must return cancel_url so clients can build cancellation links."""
    r = client.post(
        "/watch",
        json={"wiki_title": "CancelUrl_Test", "email": "cancelurl@example.com"},
    )
    # Rate limit may kick in; just check if we get a useful response
    if r.status_code == 200:
        body = r.json()
        assert "cancel_url" in body, "cancel_url must be in /watch response"
        assert "/cancel?token=" in body["cancel_url"]


# ── CAN-006: all email-generated URLs don't 404 ──────────────────────────

def test_can006_email_cancel_urls_dont_404():
    """URLs generated by email.py (/cancel?token=X and /unsubscribe) must return
    non-404 responses — confirmed without needing to send a real email."""
    # Token-based URL (GET shows confirm page)
    r1 = client.get("/cancel?token=any_test_token_123")
    assert r1.status_code != 404, "/cancel?token=... must not 404"

    # Token-less fallback URL
    r2 = client.get("/unsubscribe")
    assert r2.status_code != 404, "/unsubscribe must not 404"


# ── CAN-007: POST /unsubscribe with email and title removes subscription ─

def test_can007_post_unsubscribe_by_email():
    """POST /unsubscribe with email + wiki_title removes the subscription."""
    from app.db import add_watch, get_emails_for

    add_watch("Unsub_Form_Person", "unsubform@example.com")
    assert "unsubform@example.com" in get_emails_for("Unsub_Form_Person")

    r = client.post(
        "/unsubscribe?email=unsubform@example.com&wiki_title=Unsub_Form_Person",
    )
    assert r.status_code == 200

    remaining = get_emails_for("Unsub_Form_Person")
    assert "unsubform@example.com" not in remaining
